spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kxj_database?useUnicode=true&characterEncoding=utf8
    username: root
    password: tkp420324
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
server:
  port: 8181
